const fs = require('fs');
const path = require('path');

const appPath = path.join(__dirname, '..', 'src', 'miniapp', 'src', 'App.jsx');
const lines = fs.readFileSync(appPath, 'utf8').split('\n');

// Lines 2104..2390 (1-based) = indices 2103..2389
const newDeposit = [
'/* --- Deposit sheet 2 buttons --- */',
'',
'function DepositSheet({ view, onViewChange, method, onMethodChange, starsPacks, tonPacks, onStarsPay, onTonPay, payPending, tonWallet, tonIntent, onConnectTon, onClose }) {',
'  const [manualTon, setManualTon] = React.useState(\'\');',
'  const handleManualSend = () => {',
'    const amt = parseFloat(manualTon);',
'    if (!amt || amt <= 0) return;',
'    onTonPay({ id: \'manual\', nanoton: Math.round(amt * 1e9), coins: Math.floor(amt * 10), bonus: 0, title: amt + \' TON\' });',
'  };',
'  return (',
'    <motion.div className="dw-sheet-backdrop" onClick={onClose}',
'      initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.2 }}>',
'      <motion.div className="dw-deposit-sheet" onClick={(e) => e.stopPropagation()}',
'        initial={{ y: \'100%\' }} animate={{ y: 0 }} exit={{ y: \'100%\' }}',
'        transition={{ duration: 0.32, ease: [0.32, 0, 0, 1] }}>',
'        <div className="dw-deposit-head">',
'          <div>',
'            {view !== \'main\' && <button className="dw-back-link" style={{marginBottom:4}} onClick={() => onViewChange(\'main\')}>← Назад</button>}',
'            <h2 style={{ fontSize: 20, margin: \'2px 0\' }}>Пополнение</h2>',
'            <p style={{ color: \'var(--bone-soft)\', fontSize: 13, margin: 0 }}>1 монета = 20 ⭐ = 0.1 TON</p>',
'          </div>',
'          <button className="dw-icon-btn" onClick={onClose}>×</button>',
'        </div>',
'',
'        {view === \'main\' && !payPending && !tonIntent && (',
'          <div className="dw-deposit-choices">',
'            <button className="dw-deposit-choice" onClick={() => onViewChange(\'packs\')}>',
'              <span className="dw-deposit-choice-icon">⭐</span>',
'              <div className="dw-deposit-choice-text">',
'                <strong>Купить набор</strong>',
'                <p>Stars или TON — готовые пакеты с бонусом</p>',
'              </div>',
'              <span className="dw-deposit-choice-arrow">›</span>',
'            </button>',
'            <button className="dw-deposit-choice" onClick={() => onViewChange(\'manual\')}>',
'              <span className="dw-deposit-choice-icon">💎</span>',
'              <div className="dw-deposit-choice-text">',
'                <strong>Ввести сумму TON</strong>',
'                <p>Любая сумма, перевод напрямую</p>',
'              </div>',
'              <span className="dw-deposit-choice-arrow">›</span>',
'            </button>',
'          </div>',
'        )}',
'',
'        {view === \'packs\' && !payPending && !tonIntent && (',
'          <div>',
'            <div className="dw-deposit-tabs">',
'              <button className={`dw-deposit-tab ${method === \'stars\' ? \'active\' : \'\'}`} onClick={() => onMethodChange(\'stars\')}>⭐ Stars</button>',
'              <button className={`dw-deposit-tab ${method === \'ton\' ? \'active\' : \'\'}`} onClick={() => onMethodChange(\'ton\')}>💎 TON</button>',
'            </div>',
'            {method === \'ton\' && !tonWallet && (',
'              <div className="dw-ton-connect-block">',
'                <strong>Подключи TON кошелёк</strong>',
'                <p>Tonkeeper · MyTonWallet</p>',
'                <button className="dw-btn primary full" onClick={onConnectTon}>Подключить</button>',
'              </div>',
'            )}',
'            {(method === \'stars\' || (method === \'ton\' && tonWallet)) && (',
'              <div className="dw-pack-list">',
'                {(method === \'stars\' ? starsPacks : tonPacks).map((pack, i) => (',
'                  <motion.button className="dw-pack-row" key={pack.id}',
'                    onClick={() => method === \'stars\' ? onStarsPay(pack) : onTonPay(pack)}',
'                    initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }}',
'                    transition={{ duration: 0.18, delay: 0.04 * i }} whileTap={{ scale: 0.97 }}>',
'                    <span className="dw-pack-icon" data-icon={method === \'stars\' ? \'stars\' : \'ton\'} />',
'                    <span className="dw-pack-copy">',
'                      <strong>{pack.title}</strong>',
'                      <span>{formatCoins(pack.coins)} монет{pack.bonus > 0 ? ` + ${pack.bonus} бонус` : \'\'}</span>',
'                    </span>',
'                    <span className="dw-pack-price">{method === \'stars\' ? pack.stars + \' ⭐\' : pack.nanoton / 1e9 + \' TON\'}</span>',
'                  </motion.button>',
'                ))}',
'              </div>',
'            )}',
'          </div>',
'        )}',
'',
'        {view === \'manual\' && !payPending && !tonIntent && (',
'          <div className="dw-manual-deposit">',
'            <p style={{ color: \'var(--bone)\', fontSize: 15, marginBottom: 20, lineHeight: 1.5 }}>',
'              Переведи TON — монеты зачислятся за ~30 сек автоматически',
'            </p>',
'            <div className="dw-manual-input-row">',
'              <input className="dw-manual-input" type="number" step="0.1" min="0.1"',
'                placeholder="Сумма в TON" value={manualTon}',
'                onChange={(e) => setManualTon(e.target.value)} />',
'            </div>',
'            {manualTon && <p style={{color:\'var(--gold)\',fontSize:16,margin:\'10px 0\',textAlign:\'center\',fontWeight:700}}>{Math.floor(parseFloat(manualTon)*10)} монет</p>}',
'            <button className="dw-btn primary full" style={{ marginTop: 14 }}',
'              onClick={handleManualSend} disabled={!manualTon || parseFloat(manualTon) <= 0}>',
'              Создать счёт',
'            </button>',
'            <p style={{ color: \'var(--ash)\', fontSize: 12, marginTop: 10, textAlign: \'center\' }}>Минимум 0.1 TON</p>',
'          </div>',
'        )}',
'',
'        {payPending && (',
'          <div className="dw-pay-loading">',
'            <div className="dw-pay-spinner" />',
'            <span>Создаём счёт…</span>',
'          </div>',
'        )}',
'',
'        {tonIntent && !payPending && (',
'          <article className="dw-ton-intent">',
'            <span className="dw-kicker">Реквизиты перевода</span>',
'            <div className="dw-ton-intent-row"><span>Кошелёк</span><strong className="dw-wallet-addr">{(tonIntent.wallet||\'\'). slice(0,14)}…</strong></div>',
'            <div className="dw-ton-intent-row"><span>Сумма</span><strong>{tonIntent.amountTon} TON</strong></div>',
'            <div className="dw-ton-intent-row"><span>Комментарий</span><strong style={{fontSize:11,wordBreak:\'break-all\'}}>{tonIntent.comment||\'\'}</strong></div>',
'            <p className="dw-ton-intent-note">Отправь точную сумму с этим комментарием.</p>',
'            <div style={{ display: \'flex\', gap: 8, marginTop: 14 }}>',
'              <button className="dw-btn primary" style={{ flex: 1 }} onClick={() => {',
'                const link = `ton://transfer/${tonIntent.wallet}?amount=${tonIntent.amountNanoton}&text=${encodeURIComponent(tonIntent.comment)}`;',
'                if (window.Telegram?.WebApp?.openLink) window.Telegram.WebApp.openLink(link);',
'                else window.open(link, \'_blank\');',
'              }}>Открыть кошелёк</button>',
'              <button className="dw-btn secondary" style={{ flex: 1 }} onClick={() => navigator.clipboard?.writeText(tonIntent.comment).catch(()=>{})}>Скопировать</button>',
'            </div>',
'          </article>',
'        )}',
'      </motion.div>',
'    </motion.div>',
'  );',
'}',
];

const result = [
  ...lines.slice(0, 2103),
  ...newDeposit,
  ...lines.slice(2391)
].join('\n');

fs.writeFileSync(appPath, result);
console.log('done, total lines:', result.split('\n').length);
